### PR TITLE
adding note about breaks

### PR DESCRIPTION
**Pull request by ChristinaLK**
based on discussion at trainers meeting

### CODE REVIEW

**Comment by karenword** [comment]
@elliewix

**Comment by elliewix** [comment]
I'll want to flesh this out a bit more, but can add another PR in.

**Comment by ChristinaLK** [comment]
I'm happy to close this in favor of a more comprehensive addition.  @elliewix I put it in the notes here but if you think there's a better spot, feel free.

**Comment by ChristinaLK** [comment]
I'm going to go ahead and merge and we can add changes later.  :)

**Pull request merged**
