### PR TITLE
Updating teaching demo lang

### PR DESCRIPTION
**Pull request by sstevens2**
This is a proposed fix to issue #907

### CODE REVIEW

**Comment by karenword** [comment]
The only downside to linking to the table is that explicitly identifying episodes undermines the intent to have learners prepare a full lesson rather than (in some cases) a single episode which is the only one that happens to work well for live coding. It also gives learners the option of selecting lessons based on the number of episodes that they may have to prepare. 

The original version of this table was intended to address this need and was missing episode identification specifically for this reason -- I failed to notice that this was being lost when @maneesha ported the full table here from the handbook. I'm not sure how (or whether) to address this now. Thoughts?

**Comment by maneesha** [comment]
We do tell trainees that the demo session leader will choose any episode from within their chosen lesson.   But trainees should also feel assured that the chosen lesson will be suitable for a live coding demo -- that we won't choose something that has no live coding, or something that has dependencies. 
  I've had trainees choose a lesson that had no suitable episodes within it, and I don't want people to be in that situation.  We do want learners to prepare a full lesson, and we can emphasize that during the training.  

I think it's OK to have this here.

**Comment by sstevens2** [comment]
I think I'm alright with the option they may 'cheat' and not prepare the whole lesson.  I think trainee's typically choose their lesson based on what they are most comfortable with or planning to teach first rather than which will be the easiest to prepare.

**Comment by sstevens2** [comment]
I've also been reminding folks who sign up for my teaching demo that they need to prepare the whole lesson a day or so ahead of time.

**Comment by brownsarahm** [comment]
I thought about proposing similar changes after Lex's question yesterday and found this.  

Maybe we should also state that the lesson must include live coding or equivalent, both here and in the checkout episode?

**Comment by ErinBecker** [comment]
Hi folks - I haven't been following this issue closely, but do want to note that for some lessons, we allow trainees to use episodes that don't have live coding, per se - so long as they have something that the trainee has to work through to demo (not just talking). This includes the Spreadsheets lessons (DC Ecology, Genomics, Social Sciences, LC) and OpenRefine lessons (same curricula). It may also include other lessons I'm not aware of. So I would be cautious about saying that the episode has to have "live coding".

**Comment by brownsarahm** [comment]
@ErinBecker of course! that's what I meant by "or equivalent"  but that's probably not clear word choice. Maybe:

```
Your selected lesson must include episodes with either live coding or software demonstration, such as those included on this [list of suggested episodes](https://carpentries.github.io/instructor-training/demo_lessons/index.html).  You get to choose the lesson (the first column of the table in advance) and the trainer running your demo session will choose the specific episode for you during the session. 
```

**Comment by ErinBecker** [comment]
Thanks @brownsarahm, that language looks good to me!

**Pull request merged**
