### PR TITLE
Added suggested rubric to checkout process

### PR DESCRIPTION
**Pull request by kariljordan**
This PR addresses #941

### CODE REVIEW

**Comment by ChristinaLK** [comment]
looks good to me.

**Comment by Denubis** [comment]
Masami and I plan to use this rubric in our upcoming lesson in the "compare and contrast" request for feedback section.

**Comment by ChristinaLK** [comment]
@karenword actually, do all trainers use this (do all trainers know about it)? 
I'd almost like to email the trainers list before I put this in print. :P

**Comment by kariljordan** [comment]
> @karenword actually, do all trainers use this (do all trainers know about it)?
> I'd almost like to email the trainers list before I put this in print. :P

Great question. I didn't know about it until I taught instructor training at csv,conf with Tracy a few weeks ago!

**Comment by karenword** [comment]
I am sure that this is not used by all Trainers. We discussed it at a meeting once and a couple of emails circulated, but we've never made a big deal about it because really, it is advisory anyway. I think changing it to read "a rubric available to Trainers to aid with scoring" would make it more applicable.

**Comment by kariljordan** [comment]
I changed the wording to @karenword's recommendation.

**Comment by ChristinaLK** [comment]
Thanks @kariljordan. This looks good to me.

**Pull request merged**
