### PR TITLE
fixing links in episode 14

### PR DESCRIPTION
**Pull request by aschuerch**
I think this fixes issue #1007. Untested, though

### CODE REVIEW

**Comment by ChristinaLK** [comment]
@fmichonneau I'm still not 100% familiar w/ this jekyll shortcut -- is this the correct format?

**Comment by fmichonneau** [comment]
thanks for the report @aschuerch! 

These link issues are tricky given our setup and constraints. In general, we shouldn't use `page.root` in our lessons as the value of the variable will sometimes generate absolute paths that don't work when rendered locally.

It's difficult to debug this locally as they are many moving parts. As a first step, @carpentries/instructor-training-maintainers would you be OK with upgrading to the latest version of the template (I'll open a PR) as it attempts to fix some of these link issues. If that doesn't fix the broken links reported by Anita at least it will make it easier to find a fix. Thanks!

**Comment by ChristinaLK** [comment]
Waiting on #1009

**Comment by karenword** [comment]
This was fixed in #1022 . Thanks @aschuerch !

**Pull request closed without merging**
