### PR TITLE
add starting points for DC Image Processing

### PR DESCRIPTION
**Pull request by tobyhodges**
**Wait to merge until the curriculum has been published.**

### CODE REVIEW

**Comment by karenword** [comment]
@tobyhodges I know you know about the beta, so I'm just going to assume your timeline is compatible :) Let us know when this is ready for review!

**Comment by tobyhodges** [comment]
I am optimistic, @karenword, but also not too worried about the prospect of redoing this work if the PR needs to be closed. If you have time for a review before the curriculum has been published, that could make things moved quicker when I am ready for it to be merged...

**Comment by tobyhodges** [comment]
Also, a note that my text editor has stripped trailing whitespace off several lines in the file, which is making the diff larger than it needed to be on this pull request. For ease of reference, [the pertinent changes are on lines 106-111](https://github.com/carpentries/instructor-training/pull/1473/files#diff-e9f7e7c6145d5f5100bf7795b6ea5de97daa0fc08a5390e8c2baa3542e082d40R106-R111).

**Comment by tobyhodges** [comment]
The curriculum has now been published, so this is ready to be reviewed and merged.

**Review by ndporter — CHANGES_REQUESTED** [review]
Checked links and format and looks good. I recommend specifying JupyterLab (not just Jupyter) in notes for clarity.

**Comment by tobyhodges** [comment]
Thanks for the review, @ndporter I have updated the notes and added a link to the Jupyter Project for anyone who might need to be pointed to more information about what we mean.

**Review by karenword — APPROVED** [review]

**Pull request merged**
