### PR TITLE
Include Library Carpentry in LICENSE

### PR DESCRIPTION
**Pull request by libcce**

### CODE REVIEW

**Comment by rgaiacs** [comment]
Need to go into https://github.com/carpentries/styles.

**Comment by libcce** [comment]
I believe this has happened already https://github.com/carpentries/styles/blob/gh-pages/LICENSE.md Is there more that needs to be changed?

**Comment by rgaiacs** [comment]
> Is there more that needs to be changed?

@fmichonneau would normally make the updates to all the official lessons.

**Comment by raynamharris** [comment]
As a follow up, I noticed that the LICENSE in styles was updated in commit https://github.com/carpentries/styles/commit/55c136ca83729a27ff80d3ea332b33ce813ae417#diff-37854d19817c792316d481f5beb93cc7.  

Should we close this PR without merging or go ahead and merge it even thought changes will be incorporated later?

**Comment by raynamharris** [comment]
After getting some feedback from a fellow maintainer, we agree the best way forward it to mere here and later merge the styles repo. Thanks for your contributions @libcce!

**Pull request merged**
