### PR TITLE
Closing events on 15 and 21 Feb

### PR DESCRIPTION
**Pull request by klbarnes20**
@zkamvar This is a PR that we need to put through to the Styles version. Can you help?

### CODE REVIEW

**Comment by zkamvar** [comment]
can do!

**Comment by zkamvar** [comment]
done!

**Comment by klbarnes20** [comment]
Thanks! Is this the best way to handle these requests moving forward @zkamvar?

**Comment by zkamvar** [comment]
@klbarnes20, absolutely! Editing these events are rare enough that it's not too much trouble for me to do it.

**Comment by zkamvar** [comment]
You can merge this whenever

**Pull request merged**
