### PR TITLE
Letters to numbers for nested list rendering

### PR DESCRIPTION
**Pull request by NPalopoli**
Replaced letters by numbers (e.g. '(a)' to '1.') and accomodated spacing for appropriate display of nested list in section "Which of these questions assesses flaws in a student's mental model of a domain? You don't need to provide answers for these questions."

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Will the sublist still render as letters?  These would be preferable to numbers, as most multiple choice questions are lettered, not numbered.

**Comment by NPalopoli** [comment]
As far as I know, GitHub does not support lettered ordered lists. We could use HTML but I'd rather stick to markdown for simplicity and interoperability.

**Comment by NPalopoli** [comment]
CSS styling of sublists (nested lists) as lettered lists, to overcome limitations of kramdown. Follows suggestions by @rgaiacs (#762)

**Comment by ChristinaLK** [comment]
This looks good to me.  @rgaiacs, will this cause any problems w/ the upstream template?

**Comment by rgaiacs** [comment]
> will this cause any problems w/ the upstream template?

You need to be sure that this only applies to lists inside the exercises. So you need something like

```
blockquote.challenge ol ol,
blockquote.challenge blockquote.solution ol ol {
}
```

And because we are using SaSS, we need to have a look if you can include it inside some other block. Sorry to not provide the full solution. Trying to mentor people. :-)

**Comment by raynamharris** [comment]
Thank you @NPalopoli! I definitely agree that your proposed structure is a nice, easy fix for creating a multi-level list. However, we deleted this question entirely in PR https://github.com/carpentries/instructor-training/pull/771 because it was unnecessarily confusing to learners.

**Pull request closed without merging**
