### PR TITLE
Changed to HTTPs instead of HTTP

### PR DESCRIPTION
**Pull request by annajiat**
tiny change of adding s

### CODE REVIEW

**Comment by brownsarahm** [comment]
duplicate of #1659

**Comment by annajiat** [comment]
I'm confused and need some help. GitHub is showing that the link addressed by this PR is from SWC but the referred duplicate PR is for LC link.

**Comment by brownsarahm** [comment]
I would love to help, but for me that renders to the PR i put on this repo.

**Comment by brownsarahm** [comment]
I see now. I will merge this in.

**Pull request merged**
