### PR TITLE
Updated link to community discussions

### PR DESCRIPTION
**Pull request by kariljordan**

### CODE REVIEW

**Comment by raynamharris** [comment]
Thanks @kariljordan! We have two files regarding checkout, so I updated the second page that is in extras. Does it look okay?

**Comment by kariljordan** [comment]
This is perfect. Thank you!

**Comment by kariljordan** [comment]
@raynamharris I tried merging, but there seems to be some conflicts. Do you know how to fix them?

**Comment by raynamharris** [comment]
Thanks @kariljordan. I merged the conflicts. I think we are good to go.

**Pull request merged**
