### PR TITLE
OpenGraph details

### PR DESCRIPTION
**Pull request by mjaquiery**
Added OpenGraph meta tags, and a logo image to populate them. Included a Twitter card to display in summary format.

The description is taken from the first available of:
* page.summary
* page.questions
* page.keypoints
* generic site description

The description is truncated to 200 characters.

A .png version of the logo is saved because [Twitter does not support .svg](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary). They do ask us not to use a generic image, but it's useful in our case, I think.

This should help with #527

### CODE REVIEW

**Comment by brownsarahm** [comment]
I've requested input from the lesson infrastructure core team members to to see if this conflicts with things from styles or what the best way to handle this is.

**Comment by mjaquiery** [comment]
I wasn’t sure if it would be more useful elsewhere, but whichever way it should serve as a template for changes.

I made it here initially because the `_layouts` templates for lessons and episodes both reference the `base_layouts/.html` template, and that has `<head></head>` matter in it, meaning (to my knowledge of Jekyll) that the sites will use that header content rather than inheriting it from further downfield.

Matt Jaquiery
UKRN Coordinator for Open Research Training
DPhil Candidate (ExPsy), ACC Lab, University of Oxford

**Review by zkamvar — COMMENTED** [review]
Thank you for bringing this in! It looks like a good solution to the metadata issue (which @tobyhodges and I will be working on better standardizing across lessons later this year). I also like the fallbacks you have for the lesson and workshop descriptions.

The only conflict right now is that **this PR should be in the [carpentries/styles](https://github.com/carpentries/styles) repository** since this metadata is useful across lessons.

Other than that, here are my suggestions about the implementation:

1. The home page shows the schedule with the questions for each episode, but I think it might be better to prioritize keypoints over questions for the metadata since it will often be viewed out of context of the lesson. 
2. I believe we can use [the largest mstile favicon](https://github.com/carpentries/instructor-training/blob/gh-pages/assets/favicons/cp/mstile-310x310.png) instead of uploading a new icon. You can see how these are parsed in [_includes/favicons.html](https://github.com/carpentries/instructor-training/blob/gh-pages/_includes/favicons.html) (and maybe all of this should go in this particular file since it all goes in the `<head>` tag.

**Review by fmichonneau — COMMENTED** [review]
I agree with @zkamvar's comments. Could you please re-open this against carpentries/styles? Thanks!

**Comment by brownsarahm** [comment]
Thanks for opening it on [styles](https://github.com/carpentries/styles/pull/604) I'm closing this PR.

**Pull request closed without merging**
