### PR TITLE
first pass at how to talk about the CoC and mandated reporting

### LINKED ISSUE #659: Local Code of Conduct & Mandated Reporters
Instructors should be made aware to verify their host institution's code of conduct (as well as become familiar with the Carpentry Code of Conduct). Designating "reporters" - people participants can talk to with potential issues (including instructors/helpers and participants or hosts) - but it is also important for learners to know if any of them are "mandated reporters" (required by their institution to report).

### PR DESCRIPTION
**Pull request by ChristinaLK**
I don't feel great about this -- comments welcome.  

Maybe closes #659

### CODE REVIEW

**Comment by karenword** [comment]
I think this is probably fine for starters? I wonder if the upcoming community discussion on CoC procedures (Jan 31) might be a resource to help evaluate our language on this subject. https://pad.carpentries.org/community-discussions

**Comment by maneesha** [comment]
The CoC committee has been [making changes to the policy and reporting guidelines](https://carpentries.org/blog/2018/09/coc-revision-release/), so it would be good to check with @kariljordan  about this.

**Comment by ChristinaLK** [comment]
Sounds good. I'd be okay with waiting until after the community discussion and then doing a more coherent edit.

**Comment by karinlag** [comment]
Not sure, but I think this might also intersect with the #867 issue? My thought was that if we mention that there are resources available straight away in the first intro lesson, such as the instructor guides and the handbook, then we might mention here that the handbook has more material on CoC issues, and that we recommend people look through them before teaching.

**Pull request closed without merging**
