### PR TITLE
Activities added for roles and checkout procedures

### PR DESCRIPTION
**Pull request by amyehodge**
I have added an exercise and included a handout that goes along with it for episode 20-carpentries.

### CODE REVIEW

**Comment by amyehodge** [comment]
This PR is related to issues #568 and #569

**Comment by amyehodge** [comment]
Also, the etherpad template needs to be updated to correlate with these changes, if they are merged. Let me know what the process is and I can take care of that (though I'm offline Dec 22-Jan. 8).

**Comment by ChristinaLK** [comment]
I think this looks great! the worksheet is a nice way to engage people with that information.  :)

**Comment by karenword** [comment]
This is cool! And needed. Let's get @ErinBecker on this since it seems like this will be a defining document in addition to a helpful worksheet. Also I wonder if it would be better for the digital doc to be in pdf form?

**Comment by jduckles** [comment]
Really like the worksheet activity!

**Comment by karenword** [comment]
I'll assume that @jduckles additional approval is sufficient with regard to defining roles. Thanks @amyehodge !

**Comment by jduckles** [comment]
This does capture most of the general roles. Note we are transitioning from Steering Committee to Executive Committee in our language. My current list of the sub-groups of people in the Carpentries is as follows:

* Instructors (Mentorship) - those that teach, sharing how they teach
* Trainers - those who inspire our new instructors
* Lesson developers - those who create new lessons
* Lesson maintainers - those who support and update existing lessons
* Lesson infrastructure - those who support lesson building & styling
* Assessment - those who help us understand our impact
* Champions - those that work to spread our impact locally
* Infrastructure - those that work on support infrastructure (AMY, data analysis, surveys, sysadmins etc.)
* Workshop coordinators - those who help to coordinate workshops

I also agree that a PDF would be better than a DOCX

**Comment by amyehodge** [comment]
@karenword I can update the worksheet per @jduckles notes above.

**Comment by amyehodge** [comment]
Realizing that if I update the spreadsheet, then the list on episode 20 should be updated to match this. That work for everyone?

**Comment by ErinBecker** [comment]
Thanks @amyehodge for putting this together. I agree with @jduckles list and also that the list in episode 20 should be updated to match that list. Looks good to me to merge once those are added!

**Comment by amyehodge** [comment]
#603 PR has been submitted to cover the rest of these changes. Hopefully all is good -- I inadvertently was trying to make changes to the file in the carpentries repo the first time around. <eyes rolling>

**Pull request merged**
