### PR TITLE
add DC and SWC mission

### PR DESCRIPTION
**Pull request by raynamharris**
Added DC and SWC missions as per #785 . This doesn't add a a challenge exercise as suggested, but it does provide a little more meat in the opening paragraph. 

One thing to consider is rewriting this whole episode. I think the venn diagram and some of the lists could be condensed into 1 table, for example.

### CODE REVIEW

**Comment by raynamharris** [comment]
I know this didn't quite address #785 but is it a useful addition?

**Comment by karenword** [comment]
Yes! However, I think we need to hold for inclusion of Library Carpentry in this summary.  Also I'm still not clear on terminology -- the Carpentries is supposed to be a project (of Community Initiatives) and not an organization itself, but can we still refer to the lesson-orgs as "organizations"?

**Comment by raynamharris** [comment]
@karenword I added a sentence or two to clarify that is is a project (take from https://carpentries.org/about/)

i'm not sure what to do about adding LC. I can't find a blog post from which I can pull text....

**Comment by raynamharris** [comment]
yikes!! I was trying to resolve a merge conflict (which turned out to be caused by a change in the file name) but I didn't mean to actually merge this PR! I was blindly following the command line instructors without thinking about the consequences. 

Not sure what to do next @ChristinaLK @karenword

**Comment by karenword** [comment]
No worries @raynamharris -- I don't think there's any serious harm done here. We can leave it alone and update the language when we get more to work with on LC. There is a lot of work yet to be done with that merger, and writing these kinds of texts is on the to-do list.

**Comment by raynamharris** [comment]
I find the post about LC! https://carpentries.org/blog/2018/11/welcoming-library-carpentry/ I'll add some text about it in the relevant sections

**Pull request merged**
