### PR TITLE
Reorganize Overview to describe what Instructor training IS first, before

### PR DESCRIPTION
**Pull request by erjank**
saying what it is not.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
This looks good to me.  @karenword ?

**Comment by karenword** [comment]
I love the idea of this change! Two thoughts: 

- I suggest remove "reading pedagogical literature" since we don't really do that during the training. Maybe instead "These skills will be developed through discussion, practice, and feedback with fellow learners." ? Or something along those lines?
- I think the original intent of putting the negative first was to combat a very common misconception that this workshop teaches content (rooted in the widespread misconception that content proficiency is the most important prerequisite for effective instruction). To maintain this emphasis, I suggest bolding "not", and possibly the entire phrase "not be going over the workshop content"

**Comment by raynamharris** [comment]
(The `close and comment` button is so close to the `comment` button.)

**Comment by karenword** [comment]
Thanks @erjank and @raynamharris !

**Pull request merged**
