### PR TITLE
Updated info on Carpentries merger

### PR DESCRIPTION
**Pull request by tobyhodges**

### CODE REVIEW

**Comment by ErinBecker** [comment]
Thanks for this @tobyhodges. I'm going to hold off on merging this until Feb 1st, due to changes in our fiscal sponsorship status at that point.

**Comment by tobyhodges** [comment]
Sure! Once we're there, let me know if there's further adjustments that could be made to the wording.

**Comment by ErinBecker** [comment]
Thanks @tobyhodges! We will need to make some adjustments to the language, particularly around the word "organization" as there are legal issues with the definition of organization with our new sponsor. I'll update this after the 1st.

**Comment by kariljordan** [comment]
This looks good to me.

**Comment by ChristinaLK** [comment]
Has this task been submitted elsewhere, or should this be updated?

**Comment by ErinBecker** [comment]
Still needs to be updated, as far as I know.

**Comment by alex-konovalov** [comment]
@tobyhodges could you please update this PR to change the word 'organization' to 'project' or 'projects'? It would be useful to merge it soon, to reflect the actual state of things.

**Comment by tobyhodges** [comment]
Sorry, this had dropped off my radar completely. Should be fixed now. Can someone review please? @ErinBecker @ChristinaLK

**Comment by ErinBecker** [comment]
Looks good to me! Thanks @tobyhodges

**Comment by tobyhodges** [comment]
Reading through the Instructor Training material, there are other episodes that also refer to SWC and/or DC as organizations, so I guess this is a larger problem. I'll open an issue.

**Pull request merged**
