### PR TITLE
9.3.0 style update

### PR DESCRIPTION
**Pull request by ChristinaLK**
Only a month late.  

I'll leave open for one day but otherwise I've tested and everything looks okay.

### CODE REVIEW

**Comment by ErinBecker** [comment]
Thanks for putting this together @ChristinaLK. I'll try to preview it (if I can figure out how to locally render your branch).

**Comment by rgaiacs** [comment]
@ChristinaLK Thanks for the PR. I just noticed that you need https://github.com/swcarpentry/shell-novice/pull/678. My fault for missing instructions. You can get the file from https://raw.githubusercontent.com/swcarpentry/lesson-example/gh-pages/_extras/figures.md.

**Comment by ChristinaLK** [comment]
@rgaiacs can you confirm that I did the right thing?  

If so, then this should be ready to merge.

**Comment by rgaiacs** [comment]
> can you confirm that I did the right thing?

Looks OK to me.

> If so, then this should be ready to merge.

I will let @ErinBecker or @ChristinaLK merge.

**Pull request merged**
