### PR TITLE
Use more realistic praise example

### PR DESCRIPTION
**Pull request by gcapes**
This sounded very unnatural (at least to a UK audience).
It also contrasts nicely with the previous example, and shows the subtle difference in language promoting different mindsets.

### CODE REVIEW

**Comment by raynamharris** [comment]
Thanks @gcapes. You bring up a very good point. How slightly modifying your suggestion to say "You're naturally good at that."

**Comment by gcapes** [comment]
I'm afraid that also sounds rather unnatural to me. 

This is an example of 'performance based' praise. I don't think there's a need to imply that the origin of the ability intrinsic, is there?

**Comment by karenword** [comment]
I think the question here is how subtle we want this prompt to be -- maybe we could consider *adding* this as a prompt rather than replacing the reference to intrinsic talent?

I can see the value in encouraging people to examine the difference between saying "You're really good at that" and "You're *getting* really good at that" but that also relies on some deeper thought about the different ways that people might interpret the former. It's not immediately apparent that this kind of performance-based praise could support the belief that their performance is based on ability rather than effort (fixed mindset), but this is the negative outcome that research suggests we could avoid. 

In making the connection between praise and mindset, the most straightforward examples will include intrinsic references ("talented" or "natural"). A more challenging example will ask learners to consider how praise that doesn't directly reference intrinsic talent might be interpreted that way by someone approaching the task with a fixed mindset.

**Comment by gcapes** [comment]
Sure, we could add rather than replace *if* we can think of a natural-sounding example for intrinsic ability. The point of the exercise is to make people think about differences in wording, and how that can encourage the shift to growth mindset.

An unnatural sounding example doesn't elicit much thinking other than "I'd never say something like that anyway". Perhaps to a US audience the example sounds fine, but to a UK (/international?) audience it distracts from the point of the exercise.

**Comment by tobyhodges** [comment]
I think the phrase "You're a natural!" would be familiar to a UK audience. Not sure how universal it would be, though.

**Comment by elletjies** [comment]
> I think the phrase "You're a natural!" would be familiar to a UK audience. Not sure how universal it would be, though.

I think this will also resonate with a South Africa audience.

**Comment by gcapes** [comment]
Thanks @tobyhodges  and @elletjies 
I'll update the PR.

**Comment by karenword** [comment]
Thanks @gcapes !

**Pull request merged**
