### PR TITLE
Provided an example for the teaching demonstration

### PR DESCRIPTION
**Pull request by peranti**
I personally feel that providing an example for a lesson and segment, in the context of teaching demonstration task, would provide clarity to the instructors-in-training. At the moment, there is a scope to get confused between lesson and segment terminology, especially for the members outside the Carpentries community.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Thanks for the example @peranti - this is something that we are always trying to clarify so the feedback is helpful. 

Before merging, I'd like to rearrange the text a bit -- we have a more general explanation of what a lesson is in the next paragraph, and I feel like that information should be tied to your example. Would you be willing to review a contribution to your branch if I submit one?

**Comment by peranti** [comment]
@ChristinaLK Sure, I would review the contribution.

**Comment by ChristinaLK** [comment]
I made the change! If you can review + merge on your branch, I'll re-review here.

**Comment by ChristinaLK** [comment]
thanks @peranti ! @carpentries/instructor-training-maintainers can someone take a look and confirm that these changes are good + merge?

**Comment by brownsarahm** [comment]
Looks good to me thanks again @peranti and @ChristinaLK

**Pull request merged**
