### PR TITLE
Update guide.md

### PR DESCRIPTION
**Pull request by mikemhenry**
This is still a draft, but I'm incorporating some general tips that people shared during a trainer discussion meeting.

### CODE REVIEW

**Comment by brownsarahm** [comment]
These tips would be great to have in the notes, are you still working on this or do you want to merge it as is?

**Comment by mikemhenry** [comment]
Wow this is stale! If I don't poke at this in a week, feel free to merge it in. I think I've got a few more tips floating around in a document but if I don't find it, lets just merge this in.

**Comment by brownsarahm** [comment]
I'll try to check in a week or so, but if you decide sooner that it's done, click the ready for review button, then we can review & merge.

**Review by ChristinaLK — APPROVED** [review]
looks good to me!

**Pull request merged**
