### PR TITLE
Added Library Carpentry to the list

### PR DESCRIPTION
**Pull request by anenadic**
Added Library Carpentry to the list alongside Software and Data Carpentry.

### CODE REVIEW

**Comment by karenword** [comment]
Thanks @anenadic ! I wonder if we should include The Carpentries here now, too, and possibly adjust the language a bit more to accommodate that. @maneesha I wonder if you can weigh in on what would be the most fully accurate and least clunky way to describe all this as it applies to our collection of trademarked things?

**Comment by raynamharris** [comment]
This issue has come up again in https://github.com/carpentries/instructor-training/issues/1044. Should LC and the Carpentries be added?

**Comment by maneesha** [comment]
I am not 100% sure if all the logos are trademarked. I think 
@Talishask  can offer input from the Business team perspective.

**Comment by Talishask** [comment]
Hi @maneesha, 
Thanks for tagging me here and apologies on the delay. Not all of our logos are trademarked. I can confirm that both DC & SWC have trademarks but not LC or The Carpentries in general.

Due to transitions and then COVID-19 we postponed the trademarking project for the business team.

Let me know if you need anything else

**Comment by brownsarahm** [comment]
Should we update the keypoint to say that those two are explicitly not yet trademarked? or leave it as is for now?

**Comment by ChristinaLK** [comment]
I think closing this PR and leaving as is might be good? because the existing text is accurate.

**Comment by karenword** [comment]
Thanks @Talishask -- whenever trademarks do happen, would you please let us know so we can update? I will go ahead and close this PR for now.

**Comment by Talishask** [comment]
Yes! certainly. I've created an Asana task within the trademark project to remind me to update this page once we've updated/added trademarks.

**Pull request closed without merging**
