### PR TITLE
Add workshop layout graphics

### PR DESCRIPTION
**Pull request by davis68**
This responds to and completes #766.

I've added workshop layout graphics for SWC/DC/LC to the Carpentries overview lesson.

On my screen, the images render at an appropriate width, but we can switch to  instead of Markdown inclusion if we need to.

### CODE REVIEW

**Comment by davis68** [comment]
Currently the names are consistent with the base lesson names, or a direct abbreviation.  So one issue is that the naming schemes aren't consistent across Carpentries platforms.  Either that needs to be standardized (probably desirable, but the hard way) or we have to use alternate names here.

**Comment by libcce** [comment]
@ChristinaLK I've asked the LC Governance Group what they think about the LC chart, but if I don't hear back from them, I think I can probably comment. I just want to check with them first.

**Comment by karenword** [comment]
@davis68 what do you think about the prospects of making the colors more categorically consistent across diagrams? e.g. R/Python always being red, command line always being purple, data management type stuff always being blue etc? Also wondering whether these might be made a little bit smaller as we are worrying about the size of these -- it would be nice to be able to display them together if possible, or keep them separate but just less bulky on the page. The font size could probably be dropped without losing too much visibility, and some white space reduced?

If you don't have time for these changes that's fine -- we LOVE this idea and want to include it so we will find a way to make it work!

**Comment by davis68** [comment]
I'd used and thought of them as slides, hence the size, but let me draft up something more compact and we'll see how we like it.

**Comment by davis68** [comment]
Software Carpentry Workshop Elements
core lessons
	◐	The Unix Shell
	◐	Version Control with Git
	●	Programming with Python
	●	Plotting and Programming in Python
	●	Programming with R
	●	R for Reproducible Scientific Analysis
additional lessons
	◐	Automation and Make
	●	Programming with MATLAB
	◐	Using Databases and SQL
	◐	Version Control with Mercurial

How does this feel, suitably colored?

**Comment by davis68** [comment]
image

Here's a more compact version with better organization in labels.

**Comment by davis68** [comment]
Here is the most compact I can get them.  Preview at https://davis68.github.io/instructor-training/21-carpentries/index.html.

**Comment by karenword** [comment]
@carpentries/core-team-workshop-admin @carpentries/core-team-community I am closing this PR because we are trying to point to canonical (external) resources for things like workshop information rather than maintaining content here. However, I think these graphics do a good job of visualizing a subject that our community-members sometimes struggle with. Maybe worth considering for related content in the website update?

**Pull request closed without merging**
