### PR TITLE
Change 'coffee' to breaks to be more inclusive

### PR DESCRIPTION
**Pull request by lexnederbragt**
Not everyone drinks coffee, or even tea, and there may be cultural differences/sensitivities around this too. Too drastic?

### CODE REVIEW

**Comment by lexnederbragt** [comment]
My idea was to PR against https://github.com/data-lessons/instructor-training but Github chose otherwise. Shall I 'move' this PR over?

**Comment by ChristinaLK** [comment]
@lexnederbragt submitting it here is fine!

**Comment by raynamharris** [comment]
I agree with Christina about removing the word "short" since the time frame is specified as 15 min. 

Also, if we keep the word short, the capitalization needs to be fixed (as in "Morning Short break")

**Comment by lexnederbragt** [comment]
Like this?

 (I recently learned that to undo changes to a file in a (PR) branch, you can use, while in the (PR) branch with unwanted changes, `git checkout origin/gh-pages filename`. Soooo useful! I used it here for undoing the changes in the `_includes` folder.)

**Comment by ChristinaLK** [comment]
This looks good to me!  :D

**Pull request merged**
