### PR TITLE
add lesson for encouraging ongoing learning

### PR DESCRIPTION
**Pull request by nickp60**
Hi all!  I realize that the guidelines warn against submitting new lessons, but I think it would be worth discussing how to encourage post-workshop learning. This likely has been discussed extensively on some Etherpad or during some meeting. Here, I have outlined how I addressed some of the struggles that I had post-workshop and getting started in bioinformatics, with hopes that other community members might contribute what works for them as well.  

There is lots of support for how to host a workshop on the carpentries websites, but not much by way of supporting attendees after the workshop.  If this is deemed the wrong place to discuss post-workshop operations, perhaps some of this material could be incorporated there?

I wrote this as lesson 26, which could be used optionally if the instructor training has time.  Alternatively, some of the material could be incorporated into the earlier pedagogy lessons.

Any insight would be appreciated!

### CODE REVIEW

**Comment by karenword** [comment]
Thank you @nickp60! I love the idea of incorporating this content! For the present time, I suggest we hold on to this PR until our next curriculum push, when we can figure out a way to incorporate some of these suggestions with an actual time allowance. Maybe in [Workshop Introductions](https://carpentries.github.io/instructor-training/23-introductions/index.html)?

**Comment by ChristinaLK** [comment]
@nickp60 another suggestion might be to put this material into the Carpentries handbook for now.  I had a pile of tips for preparing for workshops and put them on this page: https://docs.carpentries.org/topic_folders/hosts_instructors/instructor_tips.html

Unfortunately the handbook isn't super visible/findable, so long-term it would be nice to have a self-contained handbook/reference for workshop prep, including how to provide for post-workshop learning.

**Comment by nickp60** [comment]
Thanks for the feedback @karenword @ChristinaLK @karinlag !  I am open to whatever solution you all deem to be most appropriate.  And I'm always looking to hear other ways that people have addressed post-worshop learning, so any added ideas would be great!

**Comment by ndporter** [comment]
Closing now that immediate fixes have been merged in #1342. No immediate plans for additional or bonus lessons.

**Pull request closed without merging**
