### PR TITLE
updates to trainer notes.  

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by raynamharris** [comment]
In my last commit I 
* fixed the hyperlinks to sections
* move some general tips from the bottom to the general section
* made all the headers title case

**Comment by ChristinaLK** [comment]
This looks good to me! @raynamharris do you want to add anything else or can @karenword review and merge?

**Comment by raynamharris** [comment]
I'm finished adding, so it's ready for review and merge.

**Comment by karenword** [comment]
Looks great! Thanks @ChristinaLK and @raynamharris !

**Comment by lexnederbragt** [comment]
Is it intentional that this PR leaves some comments marked `CK` in the instructor notes?

**Comment by karenword** [comment]
Yes! We’re trying out subjective recommendations here, with initials to indicate that these are suggestions from one trainer. This will make it easier to collect the kind of advice that is sometimes posted as an issue (until it can be addressed by curricular change) in a way that is easily findable and usable by someone preparing to teach.

**Comment by lexnederbragt** [comment]
Thanks!

**Pull request merged**
