### PR TITLE
Helpers Quick Guide

### PR DESCRIPTION
**Pull request by mtntsuchiya**
As part of my checkout process, I would like to contribute a short document covering The Carpentries teaching philosophy to be shared with helpers. I used information available on the Carpentries website and GitHub, plus some of my notes from the training. I hope that can be useful for everyone.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Thanks @mtntsuchiya ! 
This is valuable information.  

I'm not sure where this information should go in the instructor training material (or if it belongs somewhere else). This looks like a useful resource for someone running a workshop - does that sound right?

**Comment by mtntsuchiya** [comment]
Hi @ChristinaLK, 
Thank you so much! 
Yes, you are right. the idea is to provide a resource for both the instructor running the workshop and the helpers. :)

**Comment by ChristinaLK** [comment]
@mtntsuchiya I think this material would probably be best housed in the handbook (https://github.com/carpentries/handbook). We recommend that you replace the current helper checklist (https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#helper-checklist) with the material you have here -- both the checklists and teaching rules/code of conduct text.  

If you tag me in the new PR, I can support it in the handbook repo.  :)

**Comment by mtntsuchiya** [comment]
Hi @ChristinaLK , I just added the PR to the repo you suggested. 
Thanks!

**Pull request closed without merging**
