### PR TITLE
misc changes to the instructor guide

### PR DESCRIPTION
**Pull request by ChristinaLK**
Includes
* space for new material (slides + whatever else comes up)
* links at the top for trainers
* changing the minute cards link to a true template
* indenting the online teaching recommendations more sanely.  

I don't know if the internal links are going to work.

### CODE REVIEW

**Comment by remram44** [comment]
Those numbered titles are very unusual :thinking: I see that they were already here, are they really required?

**Comment by ChristinaLK** [comment]
I think @maneesha did the title formatting for the instructor's guide -- we could ask.  

There's enough headings in this document that I think numbers of some kind are useful.  If we removed them, I'd want to either split the doc into major sections or into separate pieces.

**Comment by lexnederbragt** [comment]
Or use a table of Content, which I find can be quickly generated using https://github.com/ekalinin/github-markdown-toc (it parses the markdown and generates a Markdown TOC)

**Comment by ChristinaLK** [comment]
@lexnederbragt I thought about a TOC but there's enough sections that I don't think it would be helpful, unless we did further grouping.

**Comment by ChristinaLK** [comment]
@maneesha thoughts on this? I know you put together the current version of the notes.

**Comment by ChristinaLK** [comment]
replaced by #773.

**Pull request closed without merging**
